[Include]
Include=../../modules/build/host

[Distribution]
Distribution=ubuntu
Release=resolute
Repositories=main,universe
RepositoryKeyFetch=yes

[Content]
Packages=
	    linux-modules-*-generic
	    linux-image-generic
	    linux-modules-extra-*
	    systemd
	    systemd-boot-efi
	    systemd-resolved
	    network-manager
	    plymouth
	    login.defs
	    login
	    systemd-journal-remote
	    qemu-system
	    apt
	    ovmf
	    xxd
	    python3
	    python3-dev
	    python3-pip
	    python3-emoji
	    jq
	    apt
	    avahi-daemon
	    g++
	    g++-x86-64-linux-gnu

# Remove NVIDIA Kernel Modules to reduce host RAM(initrd) size
# This strips proprietary GPU drivers that are unnecessary for this image's purpose
KernelModules=* -nvidia

# Include Required Host Kernel Modules
KernelModules=
               # Added SEV-SNP related Kernel Modules
                msr
                sev-guest

                # Added kernel modules for Networking
                af_packet
                nfnetlink
                e1000

                # Added additional Host Kernel Modules present on Ubuntu 25.10
                bnxt_re
                intel_rapl_msr
                platform_profile
                cfg80211
                ib_uverbs
                ib_core
                amd_atl
                input_leds
                joydev
                intel_rapl_common
                dell_wmi
                video
                amd64_edac
                uas
                ipmi_ssif
                dell_smbios
                sparse_keymap
                edac_mce_amd
                binfmt_misc
                ee1004
                hid_generic
                dell_wmi_descriptor
                wmi_bmof
                usb_storage
                dcdbas
                nvme
                mgag200
                polyval_clmulni
                i2c_algo_bit
                usbhid
                ghash_clmulni_intel
                nvme_core
                nvme_keyring
                hid
                rapl
                tg3
                nvme_auth
                mpt3sas
                raid_class
                ahci
                i2c_piix4
                libahci
                bnxt_en
                k10temp
                scsi_transport_sas
                i2c_smbus
                ptdma
                wmi
                acpi_power_meter
                ipmi_si
                acpi_ipmi
                ipmi_devintf
                ipmi_msghandler
                mac_hid
                kvm_amd
                cdc_ether
                ccp
                usbnet
                mii
                kvm
                sch_fq_codel
                irqbypass
                tsm_report
                msr
                efi_pstore
                dmi_sysfs
                ip_tables
                x_tables
                autofs4
                aesni_intel

[Build]
Environment=VERSION="26.04"
