[Include]
Include=../../modules/build/guest

[Distribution]
Distribution=ubuntu
Release=resolute
Repositories=main,universe
RepositoryKeyFetch=yes

[Content]
Packages=
		linux-image-generic
		linux-modules-*-generic
		linux-modules-extra-*
		systemd
		systemd-boot-efi
		systemd-resolved
		network-manager
		plymouth
		login.defs
		login
		systemd-journal-remote
		openssl
		ca-certificates
		jq
		xxd
KernelModulesExclude=.*
KernelModulesInclude=msr,sev-guest,net/


[Build]
Environment=VERSION="26.04"
