[Include]
Include=../../modules/build/guest

[Distribution]
Distribution=ubuntu
Release=resolute
Repositories=main,universe
RepositoryKeyFetch=yes

[Content]
Packages=
		linux-image-generic
		linux-modules-*-generic
		linux-modules-extra-*
		systemd
		systemd-boot-efi
		systemd-resolved
		network-manager
		plymouth
		login.defs
		login
		systemd-journal-remote
		openssl
		ca-certificates
		jq
		xxd

# Remove NVIDIA Kernel Modules to reduce guest RAM(initrd) size
# This strips proprietary GPU drivers that are unnecessary for this image's purpose
KernelModules=* -nvidia

# Include Required Guest Kernel Modules
KernelModules=
			  # Add SEV-SNP related Kernel Modules
			  msr
			  sev-guest

			  # Added Kernel Modules for Networking
			  af_packet
			  cfg80211
			  nfnetlink
			  e1000
			  ip_tables
			  e1000e

[Build]
Environment=VERSION="26.04"
